import { Role } from '@prisma/client'

type Permission = 
  | 'VIEW_ALL_EXPENSES'
  | 'ACCOUNTANT_APPROVE_EXPENSE'
  | 'ADMIN_APPROVE_EXPENSE'
  | 'MARK_PAID'
  | 'MANAGE_SITES'
  | 'MANAGE_CATEGORIES'
  | 'MANAGE_CLIENTS'
  | 'MANAGE_USERS'
  | 'MANAGE_EMPLOYEES'
  | 'VIEW_ALL_LEAVES'
  | 'APPROVE_LEAVE'
  | 'VIEW_ALL_MIRS'
  | 'STOCK_MANAGER_APPROVE_MIR'
  | 'ADMIN_APPROVE_MIR'
  | 'VIEW_ALL_ADVANCES'
  | 'ACCOUNTANT_APPROVE_ADVANCE'
  | 'ADMIN_APPROVE_ADVANCE'
  | 'VIEW_REPORTS'
  | 'VIEW_AUDIT_LOGS'
  | 'MANAGE_DATA'

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    'VIEW_ALL_EXPENSES', 'ACCOUNTANT_APPROVE_EXPENSE', 'ADMIN_APPROVE_EXPENSE',
    'MARK_PAID', 'MANAGE_SITES', 'MANAGE_CATEGORIES', 'MANAGE_CLIENTS',
    'MANAGE_USERS', 'MANAGE_EMPLOYEES', 'VIEW_ALL_LEAVES', 'APPROVE_LEAVE',
    'VIEW_ALL_MIRS', 'STOCK_MANAGER_APPROVE_MIR', 'ADMIN_APPROVE_MIR',
    'VIEW_ALL_ADVANCES', 'ACCOUNTANT_APPROVE_ADVANCE', 'ADMIN_APPROVE_ADVANCE',
    'VIEW_REPORTS', 'VIEW_AUDIT_LOGS', 'MANAGE_DATA',
  ],
  ACCOUNTANT: [
    'VIEW_ALL_EXPENSES', 'ACCOUNTANT_APPROVE_EXPENSE', 'MARK_PAID',
    'VIEW_ALL_ADVANCES', 'ACCOUNTANT_APPROVE_ADVANCE',
    'VIEW_REPORTS', 'VIEW_AUDIT_LOGS',
  ],
  STOCK_MANAGER: [
    'VIEW_ALL_MIRS', 'STOCK_MANAGER_APPROVE_MIR',
  ],
  USER: [],
}

export function checkPermission(role: string, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role as Role] || []
  return permissions.includes(permission)
}
